### ISSUE TITLE
Setup.hs `makeLibsass` assumes that `make` is GNU make

### ISSUE THREAD

**Issue by jashank** [jakubfijalkowski/hlibsass#11]
... but this assumption doesn't work on operating systems where that's not the case.
Setup.hs hard-wires `"make"`; a better heuristic might be:
if `gmake` is available, use it by preference, otherwise `make`.
(Stack does this, but uses RIO's `doesExecutableExist`.)

(I'll try to come up with a patch, but I'm not hopeful.)

**Comment by jakubfijalkowski** [comment]
I assume this is problem on *BSD system, am I right? As far as I know, every Linux distro and macOs have GNU Make and Windows "is complicated".

I think this will not be a problem (that should be just a simple `if` statement), so I'll implement it, but I won't be able to test it on real system. Will you be able to test it?

**Comment by jakubfijalkowski** [comment]
Okay, the changes are available in commit b20a035, I will be grateful if you could test it.

**Comment by jashank** [comment]
Yes (on a BSD), b20a035 fixes the build. Thanks!

**Comment by jakubfijalkowski** [comment]
Great! I will publish new version to Hackage after fixing the bug [reported in hsass repo](https://github.com/jakubfijalkowski/hsass/issues/12) (on this side only, so shouldn't be that much of a hassle for me).
