### ISSUE TITLE
Update to libsass 3.6.3

### ISSUE THREAD

**Issue by abhin4v** [jakubfijalkowski/hlibsass#13]
libsass releases 3.6 onward have a lot of new features which will be great to have in hlibsass as well.

**Comment by jakubfijalkowski** [comment]
I will try to look into it sometime this week. Last time I checked the C API hasn't changed that much so shouldn't be too much work.

**Comment by jakubfijalkowski** [comment]
Fixed with commit b0e20d9537238a0477216a3ed2ecd451c99496ae the release of [hLibsass 0.1.9.0](https://hackage.haskell.org/package/hlibsass) to Hackage.

As expected, there hasn't been much work. :)

**Comment by abhin4v** [comment]
Thank you :-)
