### ISSUE TITLE
Support for libsass 3.3.2?

### ISSUE THREAD

**Issue by peti** [jakubfijalkowski/hlibsass#3]
Hi, would it be possible to get an update of this package that supports the most recent version of libsass, which is version 3.3.2, I believe?

This request is related to https://github.com/fpco/stackage/issues/1040, FYI.

**Comment by jakubfijalkowski** [comment]
Hello.

I will try to port it during the weekend (I'm really short on time now).

**Comment by peti** [comment]
OK, very cool. Thank you!

**Comment by jakubfijalkowski** [comment]
Done, hlibsass 0.1.5.0 uses LibSass 3.3.2 (and removes bindings to the problematic functions).

**Comment by peti** [comment]
The new version works fine: http://hydra.cryp.to/job/nixpkgs/haskell-updates/haskellPackages.hlibsass.x86_64-linux.

**Comment by jakubfijalkowski** [comment]
Thanks for confirmation!
