### ISSUE TITLE
Troubles Installing on Windows10

### ISSUE THREAD

**Issue by TackB00m** [jakubfijalkowski/hlibsass#8]
Hi there, just wondering if you or anyone else out there has tried using this on Windows10. I read the installation instructions, but here's what happens:

`env: make: No such file or directory
--  While building custom Setup.hs for package hlibsass-0.1.6.1 using:
      C:\Users\Kilian\hlibsass\.stack-work\dist\ca59d0ab\setup\setup --builddir=.stack-work\dist\ca59d0ab configure --with-ghc=C:\Users\Kilian\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE --with-ghc-pkg=C:\Users\Kilian\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\62cfb14b\pkgdb --package-db=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\pkgdb --libdir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\lib --bindir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\bin --datadir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\share --libexecdir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\libexec --sysconfdir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\etc --docdir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\doc\hlibsass-0.1.6.1 --htmldir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\doc\hlibsass-0.1.6.1 --haddockdir=C:\Users\Kilian\hlibsass\.stack-work\install\6c953ab2\doc\hlibsass-0.1.6.1 --dependency=Cabal=Cabal-1.24.2.0 --dependency=base=base-4.9.1.0 --dependency=directory=directory-1.3.0.0 --extra-include-dirs=C:\Users\Kilian\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C:\Users\Kilian\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin --extra-lib-dirs=C:\Users\Kilian\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib --enable-benchmarks
    Process exited with code: ExitFailure 127`

Please correct me if i did domething wrong here.

**Comment by jakubfijalkowski** [comment]
It seems like `make` is not on your `PATH`. You must have GCC and make installed to be able to build the native library. You can use MinGW-w64 (the original MinGW is not maintained AFAIK). You may also need to adjust your PATH if the installer doesn't do it. Also, MinGW used `mingw-make` and `mingw-gcc` instead of plain `make` and `gcc` (file name is the only difference here, the apps are really just `make` and `gcc`), so you might need some symlinks BUT it might have changes since the time I looked at MinGW.

**Comment by jakubfijalkowski** [comment]
Closing since there wasn't any activity recently.
